package com.mycompany.gestorvuelos.igu;

import com.mycompany.gestorvuelos.dto.Compania;
import com.mycompany.gestorvuelos.dto.models.CompaniaTableModel;
import com.mycompany.gestorvuelos.igu.logica.CompaniaValidatorDocumentListener;
import com.mycompany.gestorvuelos.igu.logica.MaxCharsDocumentFilter;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import java.text.ParseException;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author PVita
 */
public class CompaniaDetailsPanel extends javax.swing.JPanel
{
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFrame frame = new JFrame("Formulario de Validación");
        JPanel panel = new CompaniaDetailsPanel();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(600, 400);
        frame.add(panel);
        frame.setVisible(true);
        });
    }
    
    /**
     * Creates new form CompaniaDetailsPanel
     */
    public CompaniaDetailsPanel()
    {
        initComponents();
        myCustomMethod();
    }
    
    private void myCustomMethod()
    {
        ((AbstractDocument) tfPrefijo.getDocument()).setDocumentFilter(
                new MaxCharsDocumentFilter(this, Compania.class, "prefijo"));
        ((AbstractDocument) tfCodigo.getDocument()).setDocumentFilter(
                new MaxCharsDocumentFilter(this, Compania.class, "codigo"));
        ((AbstractDocument) tfNombre.getDocument()).setDocumentFilter(
                new MaxCharsDocumentFilter(this, Compania.class, "nombre"));
        ((AbstractDocument) tfDireccionSedeCentral.getDocument()).setDocumentFilter(
                new MaxCharsDocumentFilter(this, Compania.class, "direccionSedeCentral"));
        ((AbstractDocument) tfTelefonoATA.getDocument()).setDocumentFilter(
                new MaxCharsDocumentFilter(this, Compania.class, "telefonoATA"));
        ((AbstractDocument) tfTelefonoATC.getDocument()).setDocumentFilter(
                new MaxCharsDocumentFilter(this, Compania.class, "telefonoATC"));

        tfPrefijo.getDocument().addDocumentListener(new CompaniaValidatorDocumentListener("prefijo"));
        tfCodigo.getDocument().addDocumentListener(new CompaniaValidatorDocumentListener("codigo"));
        tfNombre.getDocument().addDocumentListener(new CompaniaValidatorDocumentListener("nombre"));
        tfDireccionSedeCentral.getDocument().addDocumentListener(new CompaniaValidatorDocumentListener("direccionSedeCentral"));
        tfTelefonoATA.getDocument().addDocumentListener(new CompaniaValidatorDocumentListener("telefonoATA"));
        tfTelefonoATC.getDocument().addDocumentListener(new CompaniaValidatorDocumentListener("telefonoATC"));
    }
    
    private void saveChangesToCompania()
    {
        Compania workingCompania = new Compania();

        workingCompania.setPrefijo(Short.parseShort(tfPrefijo.getText()));
        workingCompania.setCodigo(tfCodigo.getText());
        workingCompania.setNombre(tfNombre.getText());
        workingCompania.setDireccionSedeCentral(tfDireccionSedeCentral.getText());
        
        workingCompania.setTelefonoATC(tfTelefonoATC.getText());
        workingCompania.setTelefonoATA(tfTelefonoATA.getText());
        
        var validator = Validation.buildDefaultValidatorFactory().getValidator();
        Set<ConstraintViolation<Compania>> violations = validator.validate(workingCompania);
        StringBuilder builder = new StringBuilder();
        for (ConstraintViolation<Compania> violation : violations)
        {
            builder.append(violation.getMessage()).append("\n");
        }
        if (!violations.isEmpty())
            JOptionPane.showMessageDialog(this, new String(builder));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pData = new javax.swing.JPanel();
        pCriticalData = new javax.swing.JPanel();
        lPrefijo = new javax.swing.JLabel();
        tfPrefijo = new javax.swing.JTextField();
        lCodigo = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        lNombre = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        pDireccionSedeCentral = new javax.swing.JPanel();
        lDireccionSedeCentral = new javax.swing.JLabel();
        tfDireccionSedeCentral = new javax.swing.JTextField();
        pMunicipioSedeCentral = new javax.swing.JPanel();
        lMunicipioSedeCentral = new javax.swing.JLabel();
        cbMunicipioSedeCentral = new javax.swing.JComboBox<>();
        pTelefonoATC = new javax.swing.JPanel();
        lTelefonoATA = new javax.swing.JLabel();
        tfTelefonoATA = new javax.swing.JTextField();
        lTelefonoATC = new javax.swing.JLabel();
        tfTelefonoATC = new javax.swing.JTextField();
        pActions = new javax.swing.JPanel();
        bShutdownCompania = new javax.swing.JButton();
        bSaveChangesCompania = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pData.setMinimumSize(new java.awt.Dimension(540, 168));
        pData.setPreferredSize(new java.awt.Dimension(540, 168));
        pData.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

        pCriticalData.setBackground(new java.awt.Color(232, 232, 232));
        pCriticalData.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        pCriticalData.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 5));

        lPrefijo.setText("Prefijo:");
        pCriticalData.add(lPrefijo);

        tfPrefijo.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfPrefijo.setText("999");
        tfPrefijo.setMinimumSize(new java.awt.Dimension(34, 22));
        tfPrefijo.setPreferredSize(new java.awt.Dimension(34, 22));
        pCriticalData.add(tfPrefijo);

        lCodigo.setText("Código:");
        pCriticalData.add(lCodigo);

        tfCodigo.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfCodigo.setText("WW");
        tfCodigo.setMinimumSize(new java.awt.Dimension(38, 22));
        tfCodigo.setPreferredSize(new java.awt.Dimension(38, 22));
        pCriticalData.add(tfCodigo);

        lNombre.setText("Nombre:");
        pCriticalData.add(lNombre);

        tfNombre.setText(" SAETA Soc Ecuatoriana de Ttes Aereos");
        tfNombre.setMinimumSize(new java.awt.Dimension(272, 26));
        tfNombre.setPreferredSize(new java.awt.Dimension(272, 26));
        pCriticalData.add(tfNombre);

        pData.add(pCriticalData);

        pDireccionSedeCentral.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 5));

        lDireccionSedeCentral.setText("Dirección sede central:");
        pDireccionSedeCentral.add(lDireccionSedeCentral);

        tfDireccionSedeCentral.setText("CALLE MARIA DE MOLINA, 54 , 2ª PLANTA. 28006, MADRID, MADRID");
        tfDireccionSedeCentral.setMinimumSize(new java.awt.Dimension(392, 26));
        tfDireccionSedeCentral.setPreferredSize(new java.awt.Dimension(392, 26));
        pDireccionSedeCentral.add(tfDireccionSedeCentral);

        pData.add(pDireccionSedeCentral);

        pMunicipioSedeCentral.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 5));

        lMunicipioSedeCentral.setText("Municipio sede central:");
        pMunicipioSedeCentral.add(lMunicipioSedeCentral);

        cbMunicipioSedeCentral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San Vicente del Raspeig/Sant Vicent del Raspeig" }));
        pMunicipioSedeCentral.add(cbMunicipioSedeCentral);

        pData.add(pMunicipioSedeCentral);

        pTelefonoATC.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 5));

        lTelefonoATA.setText("Teléfono ATA:");
        pTelefonoATC.add(lTelefonoATA);

        tfTelefonoATA.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfTelefonoATA.setText("+001 404555017077");
        tfTelefonoATA.setMinimumSize(new java.awt.Dimension(130, 22));
        tfTelefonoATA.setPreferredSize(new java.awt.Dimension(130, 22));
        pTelefonoATC.add(tfTelefonoATA);

        lTelefonoATC.setText("Teléfono ATC:");
        pTelefonoATC.add(lTelefonoATC);

        tfTelefonoATC.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfTelefonoATC.setText("+001 404555017066");
        tfTelefonoATC.setMinimumSize(new java.awt.Dimension(130, 22));
        tfTelefonoATC.setPreferredSize(new java.awt.Dimension(130, 22));
        pTelefonoATC.add(tfTelefonoATC);

        pData.add(pTelefonoATC);

        add(pData, java.awt.BorderLayout.CENTER);

        pActions.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        bShutdownCompania.setText("Dar de baja");
        bShutdownCompania.setEnabled(false);
        bShutdownCompania.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bShutdownCompaniaActionPerformed(evt);
            }
        });

        bSaveChangesCompania.setText("Guardar cambios");
        bSaveChangesCompania.setEnabled(false);
        bSaveChangesCompania.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bSaveChangesCompaniaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pActionsLayout = new javax.swing.GroupLayout(pActions);
        pActions.setLayout(pActionsLayout);
        pActionsLayout.setHorizontalGroup(
            pActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pActionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bShutdownCompania)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSaveChangesCompania, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pActionsLayout.setVerticalGroup(
            pActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pActionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bSaveChangesCompania, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bShutdownCompania, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pActions, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void bShutdownCompaniaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bShutdownCompaniaActionPerformed
    {//GEN-HEADEREND:event_bShutdownCompaniaActionPerformed
        
    }//GEN-LAST:event_bShutdownCompaniaActionPerformed

    private void bSaveChangesCompaniaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bSaveChangesCompaniaActionPerformed
    {//GEN-HEADEREND:event_bSaveChangesCompaniaActionPerformed
        saveChangesToCompania();
    }//GEN-LAST:event_bSaveChangesCompaniaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSaveChangesCompania;
    private javax.swing.JButton bShutdownCompania;
    private javax.swing.JComboBox<String> cbMunicipioSedeCentral;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lDireccionSedeCentral;
    private javax.swing.JLabel lMunicipioSedeCentral;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lPrefijo;
    private javax.swing.JLabel lTelefonoATA;
    private javax.swing.JLabel lTelefonoATC;
    private javax.swing.JPanel pActions;
    private javax.swing.JPanel pCriticalData;
    private javax.swing.JPanel pData;
    private javax.swing.JPanel pDireccionSedeCentral;
    private javax.swing.JPanel pMunicipioSedeCentral;
    private javax.swing.JPanel pTelefonoATC;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfDireccionSedeCentral;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPrefijo;
    private javax.swing.JTextField tfTelefonoATA;
    private javax.swing.JTextField tfTelefonoATC;
    // End of variables declaration//GEN-END:variables
}
